Traceback (most recent call last):
  File "/srv/software/spack/packages/linux-rocky9-zen4/gcc-14.2.0/miniforge3-4.8.3-4-Linux-x86_64-wceylqrywx6ca5fhcwpemr7ishol4nrv/condabin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
2025-03-18 13:45:25.033145: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:216] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Traceback (most recent call last):
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 887, in backends
    backend = _init_backend(platform)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 973, in _init_backend
    backend = registration.factory()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 673, in factory
    return xla_client.make_c_api_client(plugin_name, updated_options, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jaxlib/xla_client.py", line 200, in make_c_api_client
    return _xla.get_c_api_client(plugin_name, options, distributed_client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: No visible GPU devices.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/koehn1/fiesta/paper_fiesta/src/paper_fiesta/real_events/GRB/GRB211211A/inference_afgpy.py", line 9, in <module>
    from fiesta.inference.fiesta import Fiesta
  File "/home/koehn1/fiesta/src/fiesta/inference/fiesta.py", line 10, in <module>
    from fiesta.inference.lightcurve_model import LightcurveModel
  File "/home/koehn1/fiesta/src/fiesta/inference/lightcurve_model.py", line 16, in <module>
    import fiesta.train.neuralnets as fiesta_nn
  File "/home/koehn1/fiesta/src/fiesta/train/neuralnets.py", line 103, in <module>
    class CVAE:
  File "/home/koehn1/fiesta/src/fiesta/train/neuralnets.py", line 107, in CVAE
    key: jax.random.PRNGKey = jax.random.key(21)):
                              ^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/random.py", line 213, in key
    return _key('key', seed, impl)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/random.py", line 194, in _key
    return prng.random_seed(seed, impl=impl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/prng.py", line 533, in random_seed
    seeds_arr = jnp.asarray(np.int64(seeds))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py", line 3568, in asarray
    return array(a, dtype=dtype, copy=bool(copy), order=order, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py", line 3459, in array
    out_array: Array = lax_internal._convert_element_type(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 566, in _convert_element_type
    return convert_element_type_p.bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 2559, in _convert_element_type_bind
    operand = core.Primitive.bind(convert_element_type_p, operand,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/core.py", line 429, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/core.py", line 433, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/core.py", line 939, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koehn1/.conda/envs/fiesta/lib/python3.11/site-packages/jax/_src/dispatch.py", line 87, in apply_primitive
    outs = fun(*args)
           ^^^^^^^^^^
RuntimeError: Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices. (you may need to uninstall the failing plugin package, or set JAX_PLATFORMS=cpu to skip this backend.)
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
